# Generated by rstantools.  Do not edit by hand.

# names of stan models
stanmodels <- c("lm", "model_1_b", "model_2_br", "model_3_br", "model_4_bre", "model_5_bremn", "model_6_bremn_var", "model_6_bremn_var_mle")

# load each stan module
Rcpp::loadModule("stan_fit4lm_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model_1_b_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model_2_br_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model_3_br_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model_4_bre_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model_5_bremn_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model_6_bremn_var_mod", what = TRUE)
Rcpp::loadModule("stan_fit4model_6_bremn_var_mle_mod", what = TRUE)

# instantiate each stanmodel object
stanmodels <- sapply(stanmodels, function(model_name) {
  # create C++ code for stan model
  stan_file <- if(dir.exists("stan")) "stan" else file.path("inst", "stan")
  stan_file <- file.path(stan_file, paste0(model_name, ".stan"))
  stanfit <- rstan::stanc_builder(stan_file,
                                  allow_undefined = TRUE,
                                  obfuscate_model_name = FALSE)
  stanfit$model_cpp <- list(model_cppname = stanfit$model_name,
                            model_cppcode = stanfit$cppcode)
  # create stanmodel object
  methods::new(Class = "stanmodel",
               model_name = stanfit$model_name,
               model_code = stanfit$model_code,
               model_cpp = stanfit$model_cpp,
               mk_cppmodule = function(x) get(paste0("model_", model_name)))
})
